steps:
- name: 'gcr.io/cloud-builders/docker'
  env: ['PROJECT_ROOT=amazon-mws-tools']
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/amazon-mws-tools/apps', '.']
timeout: '1800s'
images: ['asia.gcr.io/$PROJECT_ID/amazon-mws-tools/apps']
