apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: asin-import
  labels:
    app: amazon-mws-tools
    tier: worker
spec:
  schedule: "0 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: amazon-mws-tools
        tier: worker
    spec:
      template:
        spec:
          containers:
          - name: asin-import
            image: asia.gcr.io/amazon-mws-tools/amazon-mws-tools/apps:latest
            args:
              - /app/chouhi/bin/cake
              - asin_import
          restartPolicy: OnFailure
