apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: amazon-mws-tools
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
    matchExpressions:
      - { key: tier, operator: In, values: [backend] }
  template:
    metadata:
      labels:
        app: amazon-mws-tools
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
          resources:
            requests:
              cpu: "256m"
              memory: "500Mi"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          gcePersistentDisk:
            pdName: mysql-disk
            fsType: ext4
