apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: amazon-mws-tools
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: amazon-mws-tools
    tier: backend
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
