apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: amazon-mws-tools
    tier: frontend
spec:
  selector:
    app: amazon-mws-tools
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
